---
- name: 🛠️ Mantenimiento Automático - Windows Server 2019
  hosts: windows-server
  gather_facts: no

  tasks:
    - name: 🔍 PRUEBA - Comando simple de test
      win_shell: echo "✅ Conexión SSH funcionando"
      register: test_cmd

    - name: 🧹 Limpiar archivos temporales del sistema
      win_shell: |
        Write-Output "Limpiando archivos temporales del sistema..."
        Get-ChildItem "C:\Windows\Temp\*" -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
        Get-ChildItem "C:\Temp\*" -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
        Write-Output "Limpieza de sistema completada"
      register: cleanup_system

    - name: 🧹 Limpiar archivos temporales de usuario
      win_shell: |
        Write-Output "Limpiando archivos temporales de usuarios..."
        Remove-Item -Path "C:\Users\*\AppData\Local\Temp\*" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "C:\Users\*\AppData\Local\Microsoft\Windows\INetCache\*" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "C:\Users\*\AppData\Local\Microsoft\Windows\Temporary Internet Files\*" -Recurse -Force -ErrorAction SilentlyContinue
        Write-Output "Limpieza de usuarios completada"
      register: cleanup_users

    - name: 🛡️ INSTALAR updates de Windows con método mejorado
      win_shell: |
        Write-Output "=== INSTALACIÓN MEJORADA DE UPDATES ==="
        
        # Método 1: Intentar con Windows Update nativo
        Write-Output "Método 1: Windows Update nativo..."
        $Session = New-Object -ComObject "Microsoft.Update.Session"
        $Searcher = $Session.CreateUpdateSearcher()
        
        $SearchResult = $Searcher.Search("IsInstalled=0 and Type='Software'")
        
        if ($SearchResult.Updates.Count -eq 0) {
            Write-Output "✅ No hay updates pendientes"
            exit 0
        }
        
        Write-Output "Encontrados $($SearchResult.Updates.Count) updates pendientes:"
        foreach ($Update in $SearchResult.Updates) {
            Write-Output " - $($Update.Title)"
        }
        
        # Intentar instalar con método nativo
        $Installer = $Session.CreateUpdateInstaller()
        $Installer.Updates = $SearchResult.Updates
        $InstallationResult = $Installer.Install()
        
        if ($InstallationResult.ResultCode -eq 2) {
            Write-Output "✅ Updates instalados correctamente con método nativo"
            $exitCode = 0
        } else {
            Write-Output "⚠️ Método nativo falló. Código: $($InstallationResult.ResultCode)"
            Write-Output "Intentando método alternativo..."
            
            # Método 2: Usar PowerShell cmdlets (más tolerante)
            try {
                # Para updates de Defender, usar método específico
                $defenderUpdate = $SearchResult.Updates | Where-Object { $_.Title -like "*Defender*" -or $_.Title -like "*KB2267602*" }
                if ($defenderUpdate) {
                    Write-Output "Detectada actualización de Defender, intentando método específico..."
                    
                    # Método para Defender - actualizar definiciones
                    & "C:\Program Files\Windows Defender\MpCmdRun.exe" -SignatureUpdate -Force
                    if ($LASTEXITCODE -eq 0) {
                        Write-Output "✅ Definiciones de Defender actualizadas correctamente"
                        $exitCode = 0
                    } else {
                        Write-Output "⚠️ No se pudieron actualizar definiciones de Defender"
                        $exitCode = 1
                    }
                } else {
                    Write-Output "ℹ️ No es update de Defender, continuando..."
                    $exitCode = 1
                }
            } catch {
                Write-Output "❌ Error en método alternativo: $($_.Exception.Message)"
                $exitCode = 1
            }
        }
        
        # Verificar estado final
        if ($exitCode -eq 0) {
            Write-Output "`n🎯 RESULTADO: Updates instalados/manejados correctamente"
        } else {
            Write-Output "`n⚠️ RESULTADO: Algunos updates pueden requerir intervención manual"
            Write-Output "💡 Los updates de Defender a veces fallan si el servicio está ocupado"
            Write-Output "💡 Se reintentarán automáticamente en la próxima ejecución"
        }
      register: windows_updates
      ignore_errors: yes

    - name: 📋 Mostrar resultado de actualizaciones
      debug:
        msg: "{{ windows_updates.stdout }}"

    - name: 🔍 Verificar integridad de sistema de archivos
      win_shell: |
        Write-Output "Verificando integridad del sistema de archivos..."
        sfc /verifyonly
        if ($LASTEXITCODE -eq 0) {
          Write-Output "✅ SFC: No se encontraron problemas de integridad"
        } else {
          Write-Output "⚠️ SFC: Se detectaron problemas. Ejecutar 'sfc /scannow' manualmente"
        }
      register: sfc_check

    - name: 📈 Verificar rendimiento del sistema
      win_shell: |
        Write-Output "=== MONITOREO DE RENDIMIENTO ==="
        
        # Espacio en disco
        $disk = Get-PSDrive C | Select-Object Used, Free, @{Name="UsedGB";Expression={[math]::Round($_.Used/1GB,2)}}, @{Name="FreeGB";Expression={[math]::Round($_.Free/1GB,2)}}
        Write-Output "Disco C - Usado: $($disk.UsedGB) GB, Libre: $($disk.FreeGB) GB"
        
        # Memoria
        $memory = Get-WmiObject Win32_OperatingSystem
        $freeMemory = [math]::Round($memory.FreePhysicalMemory / 1MB, 2)
        $totalMemory = [math]::Round($memory.TotalVisibleMemorySize / 1MB, 2)
        Write-Output "Memoria - Libre: $freeMemory GB, Total: $totalMemory GB"
        
        # Versión actual de Defender
        try {
            $defenderVersion = & "C:\Program Files\Windows Defender\MpCmdRun.exe" -GetFiles
            Write-Output "Defender: Ejecutándose correctamente"
        } catch {
            Write-Output "Defender: Información no disponible"
        }
      register: performance_check

    - name: 📊 Verificar servicios críticos
      win_shell: |
        Write-Output "=== ESTADO DE SERVICIOS CRÍTICOS ==="
        $services = @("Spooler", "EventLog", "LanmanServer", "LanmanWorkstation", "Dhcp", "Dnscache", "WinDefend")
        foreach ($service in $services) {
          $status = Get-Service -Name $service -ErrorAction SilentlyContinue
          if ($status) {
            Write-Output "$service : $($status.Status)"
          } else {
            Write-Output "$service : No encontrado"
          }
        }
      register: services_check

    - name: 🗑️ Limpiar logs antiguos de Event Viewer
      win_shell: |
        Write-Output "Limpiando logs antiguos de Event Viewer..."
        $logs = @("Application", "System", "Security")
        foreach ($log in $logs) {
          try {
            wevtutil cl $log
            Write-Output "Log limpiado: $log"
          } catch {
            Write-Output "Error limpiando log $log : $($_.Exception.Message)"
          }
        }
        Write-Output "Limpieza de logs completada"
      register: event_cleanup

    - name: 📝 Generar reporte de mantenimiento
      win_shell: |
        $fecha = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $computer = $env:COMPUTERNAME
        
        $reporte = "REPORTE DE MANTENIMIENTO - $fecha`nEquipo: $computer`n`nTareas completadas:`n✅ Limpieza archivos temporales`n✅ Gestión de updates de Windows`n✅ Verificación integridad SFC`n✅ Monitoreo de rendimiento`n✅ Verificación de servicios críticos`n✅ Limpieza de logs de Event Viewer`n`nEjecutado desde Ansible Semaphore`n`nNota: Los updates de Defender se reintentan automáticamente"
        $reporte | Out-File "C:\Temp\reporte-mantenimiento.txt" -Encoding UTF8
        Write-Output "Reporte generado en C:\Temp\reporte-mantenimiento.txt"
      register: reporte

    - name: ✅ FINALIZADO
      debug:
        msg: "✅ Mantenimiento Windows completado en {{ inventory_hostname }}"
