---
- name: 🛠️ Mantenimiento Servidor FTP Windows 2016
  hosts: oliftp-windows
  gather_facts: yes

  tasks:
    - name: 1. PRUEBA DE CONEXIÓN
      win_ping:

    - name: 2. INFORMACIÓN DEL SISTEMA
      win_command: systeminfo
      register: system_info

    - name: Mostrar información básica
      debug:
        msg: |
          Servidor FTP: {{ inventory_hostname }}
          Sistema: Windows Server 2016 Standard
          IP: 192.168.0.36
          Fecha: {{ ansible_date_time.date }}

    - name: 3. ANÁLISIS DE DISCOS
      win_shell: |
        Get-PSDrive -PSProvider FileSystem | 
        Select-Object Name,
          @{Name="UsedGB";Expression={[math]::Round($_.Used/1GB,2)}},
          @{Name="FreeGB";Expression={[math]::Round($_.Free/1GB,2)}},
          @{Name="TotalGB";Expression={[math]::Round(($_.Used + $_.Free)/1GB,2)}}
      register: disk_analysis

    - name: Mostrar estado discos
      debug:
        msg: "{{ disk_analysis.stdout }}"

    - name: 4. BUSCAR DIRECTORIOS BACKUP
      win_shell: |
        $drives = Get-PSDrive -PSProvider FileSystem | Select-Object -ExpandProperty Root
        $patterns = @("*backup*", "*cobian*", "*Backup*", "*Cobian*")
        foreach ($drive in $drives) {
          if (Test-Path $drive) {
            foreach ($pattern in $patterns) {
              $dirs = Get-ChildItem -Path $drive -Directory -Filter $pattern -ErrorAction SilentlyContinue
              if ($dirs) {
                foreach ($dir in $dirs) {
                  Write-Output "Encontrado: $($dir.FullName)"
                }
              }
            }
          }
        }
      register: backup_search
      changed_when: false

    - name: Mostrar resultados búsqueda
      debug:
        msg: "{{ backup_search.stdout }}"

    - name: 5. LIMPIEZA TEMPORALES
      win_shell: |
        $paths = @("C:\Windows\Temp", "C:\Temp", "$env:TEMP")
        $total = 0
        foreach ($path in $paths) {
          if (Test-Path $path) {
            $files = Get-ChildItem -Path $path -Recurse -File -ErrorAction SilentlyContinue | 
                    Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-30) }
            if ($files.Count -gt 0) {
              $files | Remove-Item -Force -ErrorAction SilentlyContinue
              $total += $files.Count
            }
          }
        }
        Write-Output "Archivos limpiados: $total"
      register: temp_cleanup
      changed_when: "temp_cleanup.stdout is search('limpiados')"

    - name: Mostrar resultado limpieza
      debug:
        msg: "{{ temp_cleanup.stdout }}"

    - name: 6. VERIFICAR SERVICIOS
      win_shell: |
        $services = @("Spooler", "EventLog", "LanmanServer", "LanmanWorkstation")
        foreach ($service in $services) {
          $status = Get-Service -Name $service -ErrorAction SilentlyContinue
          if ($status) {
            Write-Output "$service : $($status.Status)"
          }
        }
      register: service_check
      changed_when: false

    - name: Mostrar estado servicios
      debug:
        msg: "{{ service_check.stdout }}"

    - name: 7. CREAR REPORTE SIMPLE
      win_shell: |
        $report = "C:\Temp\ftp-report.txt"
        Get-Date | Out-File $report
        hostname | Out-File $report -Append
        Write-Output "Reporte creado: $report"
      register: create_report
      changed_when: false

    - name: Mostrar ubicación reporte
      debug:
        msg: "Reporte creado en C:\\Temp\\ftp-report.txt"  # CORREGIDO: barras escapadas

    - name: 8. FINALIZACIÓN
      debug:
        msg: "Mantenimiento FTP completado exitosamente"
