---
- name: 🛠️ Mantenimiento Automático - Windows Server 2019
  hosts: windows-server
  gather_facts: no

  tasks:
    - name: 🔍 PRUEBA - Comando simple de test
      win_shell: echo "✅ Conexión SSH funcionando"
      register: test_cmd

    - name: 🧹 Limpiar archivos temporales del sistema
      win_shell: |
        Write-Output "Limpiando archivos temporales del sistema..."
        Get-ChildItem "C:\Windows\Temp\*" -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
        Get-ChildItem "C:\Temp\*" -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
        Write-Output "Limpieza de sistema completada"
      register: cleanup_system

    - name: 🧹 Limpiar archivos temporales de usuario
      win_shell: |
        Write-Output "Limpiando archivos temporales de usuarios..."
        Remove-Item -Path "C:\Users\*\AppData\Local\Temp\*" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "C:\Users\*\AppData\Local\Microsoft\Windows\INetCache\*" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "C:\Users\*\AppData\Local\Microsoft\Windows\Temporary Internet Files\*" -Recurse -Force -ErrorAction SilentlyContinue
        Write-Output "Limpieza de usuarios completada"
      register: cleanup_users

    - name: 🛡️ INSTALAR TODOS los updates de Windows (sin reinicio automático)
      win_shell: |
        Write-Output "=== INSTALACIÓN DE UPDATES (SIN REINICIO AUTOMÁTICO) ==="
        
        # Método nativo de Windows
        $Session = New-Object -ComObject "Microsoft.Update.Session"
        $Searcher = $Session.CreateUpdateSearcher()
        
        Write-Output "Buscando updates pendientes..."
        $SearchResult = $Searcher.Search("IsInstalled=0 and Type='Software'")
        
        if ($SearchResult.Updates.Count -eq 0) {
            Write-Output "✅ No hay updates pendientes"
            exit 0
        }
        
        Write-Output "Encontrados $($SearchResult.Updates.Count) updates pendientes:"
        foreach ($Update in $SearchResult.Updates) {
            Write-Output " - $($Update.Title)"
        }
        
        # INSTALAR TODOS los updates pero SIN reinicio automático
        Write-Output "Instalando TODOS los updates (sin reinicio automático)..."
        $Installer = $Session.CreateUpdateInstaller()
        $Installer.Updates = $SearchResult.Updates
        $InstallationResult = $Installer.Install()
        
        if ($InstallationResult.ResultCode -eq 2) {
            Write-Output "✅ TODOS los updates instalados correctamente"
            Write-Output "📋 Updates instalados:"
            foreach ($Update in $SearchResult.Updates) {
                Write-Output "   - $($Update.Title)"
            }
        } else {
            Write-Output "⚠️ Algunos updates no se pudieron instalar. Código: $($InstallationResult.ResultCode)"
        }
      register: windows_updates
      ignore_errors: yes

    - name: 📋 Mostrar resultado de actualizaciones
      debug:
        msg: "{{ windows_updates.stdout }}"

    - name: 🚨 VERIFICAR si se requiere reinicio después de la instalación
      win_shell: |
        Write-Output "=== VERIFICACIÓN DE REINICIO POST-INSTALACIÓN ==="
        
        $rebootRequired = $false
        $methods = @()
        
        # Método 1: Windows Update
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired") {
            $rebootRequired = $true
            $methods += "Windows Update"
        }
        
        # Método 2: Component Based Servicing
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending") {
            $rebootRequired = $true
            $methods += "Component Based Servicing"
        }
        
        # Método 3: Pending File Rename Operations
        try {
            $pendingRename = Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" -Name "PendingFileRenameOperations" -ErrorAction SilentlyContinue
            if ($pendingRename -and $pendingRename.PendingFileRenameOperations -ne $null) {
                $rebootRequired = $true
                $methods += "Pending File Rename Operations"
            }
        } catch { }
        
        # Método 4: WMI
        try {
            $wmiReboot = (Get-WmiObject -Class Win32_OperatingSystem).RebootRequired
            if ($wmiReboot) {
                $rebootRequired = $true
                $methods += "WMI"
            }
        } catch { }
        
        if ($rebootRequired) {
            Write-Output "🚨 ATENCIÓN: REINICIO REQUERIDO después de instalar updates"
            Write-Output "📋 Métodos que detectan reinicio: $($methods -join ', ')"
            Write-Output "⏰ Por favor programe el reinicio MANUAL fuera del horario de producción"
            Write-Output "💡 Comando para reiniciar: Restart-Computer -Force"
        } else {
            Write-Output "✅ No se requiere reinicio - sistema listo para usar"
        }
        
        Write-Output "`n=== RESUMEN FINAL ==="
        Write-Output "Updates instalados: $($SearchResult.Updates.Count)"
        Write-Output "Reinicio requerido: $(if ($rebootRequired) { 'SI' } else { 'NO' })"
      register: reboot_check

    - name: 📋 Mostrar estado de reinicio
      debug:
        msg: "{{ reboot_check.stdout }}"

    - name: 🔍 Verificar integridad de sistema de archivos
      win_shell: |
        Write-Output "Verificando integridad del sistema de archivos..."
        sfc /verifyonly
        if ($LASTEXITCODE -eq 0) {
          Write-Output "✅ SFC: No se encontraron problemas de integridad"
        } else {
          Write-Output "⚠️ SFC: Se detectaron problemas. Ejecutar 'sfc /scannow' manualmente"
        }
      register: sfc_check

    - name: 📈 Verificar rendimiento del sistema
      win_shell: |
        Write-Output "=== MONITOREO DE RENDIMIENTO ==="
        
        # Espacio en disco
        $disk = Get-PSDrive C | Select-Object Used, Free, @{Name="UsedGB";Expression={[math]::Round($_.Used/1GB,2)}}, @{Name="FreeGB";Expression={[math]::Round($_.Free/1GB,2)}}
        Write-Output "Disco C - Usado: $($disk.UsedGB) GB, Libre: $($disk.FreeGB) GB"
        
        # Memoria
        $memory = Get-WmiObject Win32_OperatingSystem
        $freeMemory = [math]::Round($memory.FreePhysicalMemory / 1MB, 2)
        $totalMemory = [math]::Round($memory.TotalVisibleMemorySize / 1MB, 2)
        Write-Output "Memoria - Libre: $freeMemory GB, Total: $totalMemory GB"
      register: performance_check

    - name: 📊 Verificar servicios críticos
      win_shell: |
        Write-Output "=== ESTADO DE SERVICIOS CRÍTICOS ==="
        $services = @("Spooler", "EventLog", "LanmanServer", "LanmanWorkstation", "Dhcp", "Dnscache")
        foreach ($service in $services) {
          $status = Get-Service -Name $service -ErrorAction SilentlyContinue
          if ($status) {
            Write-Output "$service : $($status.Status)"
          } else {
            Write-Output "$service : No encontrado"
          }
        }
      register: services_check

    - name: 🗑️ Limpiar logs antiguos de Event Viewer
      win_shell: |
        Write-Output "Limpiando logs antiguos de Event Viewer..."
        $logs = @("Application", "System", "Security")
        foreach ($log in $logs) {
          try {
            wevtutil cl $log
            Write-Output "Log limpiado: $log"
          } catch {
            Write-Output "Error limpiando log $log : $($_.Exception.Message)"
          }
        }
        Write-Output "Limpieza de logs completada"
      register: event_cleanup

    - name: ✅ FINALIZADO
      debug:
        msg: "✅ Mantenimiento Windows completado en {{ inventory_hostname }}"
